### ISSUE TITLE
Awesome Project!

### ISSUE THREAD

**Issue by Maynardnaze** [Brets0150/pwnagotchi-to-hashtopolis-plugin#1]
No issues at all. Thanks for putting this together. 
Smooth as butter. I did need this command after install hcxtools.

 sudo ln -s /usr/local/bin/hcxpcapngtool /usr/local/bin/hcxpcaptool

Thank you!

**Comment by Brets0150** [comment]
Hey, thanks for trying out Pwn2Crack! 
That is odd; Pwn2Crack does not use the older "hcxpcaptool" tool; it only uses the new version "hcxpcap**ng**tool." So I am not sure why you needed to make a sym-link for the older version? Anyways, glad it works, though.
